version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local # local -> host machine, remote -> cloud
    name: wp
    driver_opts:
      type: none
      o: bind # o -> option, bind -> mount type yani host machine ile container arasinda baglantiyi belirler.
      device: /$HOME/data/wordpress # Bu kisimda host machine'de olusturulacak olan volume'un path'i belirtilir.
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/mariadb # Burayi yazmazsaniz default olarak /var/lib/docker/volumes/... seklinde olusturulur.

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped # containet durdugunda veya coktugunde otomatik olarak baslatilir. Ancak manuel olarak durduruldugunda baslatilmaz.

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress # wordpress container'i calismaya basladiktan sonra nginx container'i calismaya baslar.
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
